import type { LauncherState } from './types'

export const initialState: LauncherState = {
  activeProfileId: 'feather-performance',
  profiles: [
    {
      id: 'feather-performance',
      name: 'Feather Performance',
      version: '1.21.5',
      loader: 'Fabric',
      loaderVersion: '0.16.14',
      memoryMb: 4096,
      icon: 'FP',
      color: '#8b5cf6',
      lastPlayed: 'Today',
    },
    {
      id: 'forge-survival',
      name: 'Forge Survival',
      version: '1.20.1',
      loader: 'Forge',
      loaderVersion: '47.4.0',
      memoryMb: 6144,
      icon: 'FS',
      color: '#06b6d4',
      lastPlayed: '3 days ago',
    },
    {
      id: 'vanilla-latest',
      name: 'Latest Vanilla',
      version: '1.21.5',
      loader: 'Vanilla',
      loaderVersion: '',
      memoryMb: 3072,
      icon: 'VL',
      color: '#22c55e',
      lastPlayed: 'Never',
    },
  ],
  mods: [
    {
      id: 'fps-counter',
      name: 'FPS Counter',
      description: 'Clean real-time framerate monitor with average and 1% lows.',
      category: 'HUD',
      version: '1.0.0',
      enabled: true,
      builtIn: true,
    },
    {
      id: 'keystrokes',
      name: 'Keystrokes',
      description: 'Customizable WASD, mouse buttons, and spacebar overlay.',
      category: 'HUD',
      version: '1.0.0',
      enabled: true,
      builtIn: true,
    },
    {
      id: 'toggle-sprint',
      name: 'Toggle Sprint',
      description: 'Toggle sprint or sneak with configurable keybinds.',
      category: 'Utility',
      version: '1.0.0',
      enabled: true,
      builtIn: true,
    },
    {
      id: 'armor-hud',
      name: 'Armor HUD',
      description: 'Durability and equipped armor status at a glance.',
      category: 'HUD',
      version: '1.0.0',
      enabled: true,
      builtIn: true,
    },
    {
      id: 'zoom',
      name: 'Smooth Zoom',
      description: 'Cinematic zoom with sensitivity and animation controls.',
      category: 'Utility',
      version: '1.0.0',
      enabled: true,
      builtIn: true,
    },
    {
      id: 'fullbright',
      name: 'Fullbright',
      description: 'Visibility controls for dark areas and night gameplay.',
      category: 'Utility',
      version: '1.0.0',
      enabled: false,
      builtIn: true,
    },
    {
      id: 'memory-optimizer',
      name: 'Memory Optimizer',
      description: 'Smoother chunk loading and conservative memory cleanup.',
      category: 'Performance',
      version: '1.0.0',
      enabled: true,
      builtIn: true,
    },
    {
      id: 'voice-chat',
      name: 'Voice Chat',
      description: 'Integration point for proximity and party voice providers.',
      category: 'Social',
      version: '0.1.0',
      enabled: false,
      builtIn: true,
    },
  ],
  settings: {
    gameDirectory: '',
    javaPath: '',
    memoryMb: 4096,
    resolutionWidth: 1280,
    resolutionHeight: 720,
    closeOnLaunch: false,
    autoConnectVoice: true,
    showSnapshots: false,
    launchArguments: '-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions',
    theme: 'dark',
  },
  account: {
    connected: false,
    username: '',
    uuid: '',
    avatarSeed: 'steve',
  },
  playMinutes: 0,
  launches: 0,
}

export const releaseNotes = [
  {
    tag: 'PERFORMANCE',
    title: 'A faster launcher foundation',
    description:
      'Native Tauri runtime, local-first profiles, and a focused launch preflight.',
    date: 'MVP 0.1',
    accent: 'violet',
  },
  {
    tag: 'MODS',
    title: 'One place for every profile',
    description:
      'Keep Fabric, Forge, and vanilla configurations separate and predictable.',
    date: 'MVP 0.1',
    accent: 'cyan',
  },
]
